### ISSUE TITLE
Subset of codes raise exception

### ISSUE THREAD

**Issue by cplotter** [mathieuprog/mobile_number_format#1]
The following codes raise an exception when calling:

```elixir
MobileNumberFormat.parse(%{national_number: "~anynumber~", country_calling_code: "+253"})
```

>   (FunctionClauseError) no function clause matching in String.replace_prefix/3 
    (elixir 1.13.0) lib/string.ex:1084: String.replace_prefix/3
    (mobile_number_format 0.1.0) lib/compiler.ex:280: anonymous fn/3 in MobileNumberFormat.do_parse/3 
    (elixir 1.13.0) lib/enum.ex:4075: Enum.find_value_list/3
    (mobile_number_format 0.1.0) lib/compiler.ex:280: MobileNumberFormat.do_parse/3

+253
+351
+65
+678
etctera

**Comment by mathieuprog** [comment]
Thank you for reporting this issue!

This happened because these countries don't have any national prefix, which the code didn't expect.
I have corrected this and released v0.2.0

Could you try to run the new version against your code and give me feedback?
